### ISSUE TITLE
[login] improve error message in order to be more user-friendly

### ISSUE THREAD

**Issue by diegoberaldin** [diegoberaldin/RaccoonForLemmy#1005]
Instead of putting the error body in the system notification like barbarians do, decode the response and display a useful and understandable message even for non "tech savvy" users.

**Comment by N7-X** [comment]
I've been investigating this, and it looks like the error message in the app is caused by the API only returning `error "incorrect_login"` when LoginResponse has `registration_created` and `verify_email_sent` as non-nullable. 
Of course that's the way it's supposed to be handled, [according to the documentation](https://join-lemmy.org/api/interfaces/LoginResponse.html) so that's not really a RaccoonForLemmy issue. 

I temporarily bypassed this for testing purposes to get the "real" error message(s) by allowing both values to be nullable, and adding `error` as another property in LoginResponse. 
Finally, under DefaultLoginUseCase.kt I put a check for `it.error != null` to throw the value in an exception so it appears in the notification. 
The only error message I was able to consistently get from the API was "incorrect_login" even after trying a variety of wrong/correct/too long values for username and password. 
Looking at [lemm.ee login](https://lemm.ee/login), they do the check for =< 60 characters on the client side, and bypassing that just spins indefinitely. 

So with all of that in mind, I'm not actually sure if there are enough responses to decode and display to the user. 
I do think it may be worth exploring if the json response has only the "error" property, and handling that message in some way. 

What do you think?  There may be details I missed or an even easier solution, so please don't hesitate to correct me!

**Comment by diegoberaldin** [comment]
Yes, that is the correct way! `registrationCreated` and `verifyEmailSent` should be nullable and a new `error` field should be added, then the exception should be thrown in `DefaultLoginUseCase` so that `LoginViewModel` can retrieve it ( `result.exceptionOrNull()`) and display the error message to users.

**Comment by N7-X** [comment]
Well in that case, I'll clean up my work and start the process of submitting a pull request, either today after work or sometime tomorrow.

**Comment by diegoberaldin** [comment]
Closed by #1010 and #1011.
