### ISSUE TITLE
All settings get reset upon login 

### ISSUE THREAD

**Issue by everdred** [diegoberaldin/RaccoonForLemmy#111]
Settings that have been changed while logged out and browsing anonymously are all reset to their defaults when you sign in to an account.

**Comment by diegoberaldin** [comment]
This was "expected" since every account (even anonymous one) has its own indepenent settings. You can log out or switch acccount and you should find all your previous settings, whereas every time you create an account you start with the default values.

But I agree that for a user it looks like a bug, due to all preferences being seemingly "lost". I'll change this behaviour and copy the settings from the anonymous account to each newly created one.

**Comment by everdred** [comment]
Gotcha, I can understand your perspective on this, and I think your solution makes sense. It may have only felt lost because the default anonymous "account" becomes inaccessible once the user has added their first logged-in account.

**Comment by diegoberaldin** [comment]
Well... my assumption was wrong, but copying the settings like I did should be enough to avoid that poor UX. Thank you for reporting! 🙏 

More improvements for the anonymous mode (and easier login) are coming soon, as per #116. I also realized that I accidentally allowed some actions (such as report and hide read/clear read) even for anonymous users, this is going to be corrected as part of #117.

PS: The anonymous status is available again after logging out from the current account.
