### ISSUE TITLE
Missing subscribe button when following Lemmy community link from "About this app"

### ISSUE THREAD

**Issue by Zectivi** [diegoberaldin/RaccoonForLemmy#450]
Hello again!

Device: Pixel 8 Pro
OS: GrapheneOS (latest release, based on Android 14)
App version: 1.5.1 (66)

Tested from both my Lemmy.world and sh.itjust.works accounts. 

When following the "Lemmy community" link from Settings > About this app, the subscribe button is missing. If I subscribe from another interface and follow the Lemmy community link again from settings, the checkmark is present and I can toggle it back and forth. If I unsubscribe and return to settings and follow the community link again, the checkmark is missing. 

Additionally, and possibly of a lesser concern, from the above "raccoonforlemmy" community view, tapping the 3 dot overflow and tapping instance details, none of the communities shown can be subscribed to. 

This is not an issue in the Explore tab.

Steps to reproduce:

1. Settings tab
2. Scroll to the bottom and tap About this app
3. Tap Lemmy community link
4. Unable to subscribe to the raccoonforlemmy community

**Missing subscribe option**: 

![Screenshot_20240115-221539](https://github.com/diegoberaldin/RaccoonForLemmy/assets/133516047/6cf26ea0-534f-47fa-9ab8-77fea05c7c76)

**"Subscribed" after doing it from another app/website:**

![Screenshot_20240115-221617](https://github.com/diegoberaldin/RaccoonForLemmy/assets/133516047/699ae0c4-1ea0-4fd5-b268-2f5394374a88)

**Able to toggle the subscription:**

![Screenshot_20240115-221630](https://github.com/diegoberaldin/RaccoonForLemmy/assets/133516047/718ee065-6cf0-48da-b3f3-154f17428b77)

**Comment by diegoberaldin** [comment]
Thanks for reporting. Unfortunately it is something that I knew (and left it for when I had more time): the behavior you describe is due to visiting the community in guest mode, as if you didn't have an account on the respective instance. Therefore, in guest mode, you can not subscribe nor vote/comment/post.

I agree with you that this is far from optimal (translation: "it sucks") because if someone opens the community from the "About" dialog it's natural that they want to subscribe and interact with the community or post contents.

The reason why the guest mode is enforced is that, for logged users, it is nontrivial to trace back the correct community from the instance where the user is logged (and due to how federation works it may even never be found since community loading is lazy). And when I implemented the about dialog I thought this was a secondary concern. Sorry 😅

I'll look into it asap.

**Comment by diegoberaldin** [comment]
I am fixing the possibility to retain the logged user and the current instance (to avoid "guest mode") in #452. The possibility to subscribe to communities from the "Instance details" info page is not going to change, though, and is related to #33.

**Comment by Zectivi** [comment]
Sounds great! I appreciate the app and the work you put into it!
