### ISSUE TITLE
[post list] Full width image thumbnail (feature request)

### ISSUE THREAD

**Issue by cloudlessx** [diegoberaldin/RaccoonForLemmy#746]
Current behaviour:
- Thumbnails are shown in a box with rounded corners and margins

Preferred behaviour:
- Provide an option to show thumbnails using the full width of the screen, without margins

**Comment by cloudlessx** [comment]
Oh I have been using the card layout and didn't even realise there is a "Full" layout. I tried it just now and quite like it.

Even in "Full" layout, images still have some margins on the left and right sides. This might be good for some phones with curved screen. On a flat screen I don't see any point to leave the margins. Would prefer if there is an option to remove the margins (left & right). That should be independent of the "Full height images" setting.

I prefer to have limited height images (to keep scrolling through posts consistent), but with maximum width (no wasted screen space).

**Comment by diegoberaldin** [comment]
Ok I got the idea and will add an option to remove all margins to images. I will have to touch a lot of points because the padding was not in the image component but in the list itself (this is why even in "Full" mode you get some horizontal padding) and will have to move everything from the list to the image. But it can be done.
