### ISSUE TITLE
feature request for upvoting while swiping to the right

### ISSUE THREAD

**Issue by lollocosta123** [diegoberaldin/RaccoonForLemmy#756]
Hi, thank you for the great app.

As you might know, on some instances downvotes are disabled, while changing the swipe functionality I saw that is not possible to swipe both directions to upvote. 

The upvote functionality should in my opinion be available even when swiping to the right.

![Screenshot_2024-05-02-09-01-27-691_com github diegoberaldin raccoonforlemmy android-edit](https://github.com/diegoberaldin/RaccoonForLemmy/assets/88317690/38f640e3-3dfd-42c8-ae10-7e30b4fe1efb)

**Comment by diegoberaldin** [comment]
I see... as of now, you can use actions at most once for each category (posts, comments or inbox) so if you assign one to the left you won't be able to reuse it on the right and vice versa. You would like to be able to assign it multiple times, which is surely possible and easy, because I'll have to just undo the logic that removes the action from the available "pool".

I agree in that the app is "constraining" users so I am in favor of removing that constraint. Let's wait some time to see if anyone has anything against this proposal and, if nobody tells anything, I am going to allow multiple assignment for actions on both sides.

**Comment by diegoberaldin** [comment]
@cloudlessx considering you are very active and have probably more common sense than I do, can I ask your opinion about this one? Would you allow duplicated actions on both sides? I can only limit the possibility of assigning twice the same action on the same side which does not make sense to me, but allow multiple assignments on different sides.

**Comment by cloudlessx** [comment]
@diegoberaldin Yes. I think users should be allowed to customise gestures exactly the way they like. I am not a fan of swipes but the one I use in Outlook is swipe to mark message as read.  I set both swipe left and swipe right as read because I don't want to remember which swipe is the correct swipe.
