### ISSUE TITLE
[feature request] add user avatar to comments

### ISSUE THREAD

**Issue by pfaca** [diegoberaldin/RaccoonForLemmy#798]
It would be cool if we had an option to see the user avatar in the comments.

Other QoL that would help is having some kind of tag/icon(like the OP one) after the username showing if the account is a bot and other for the new users (based in the account time). Voyager does both, icon for bots and a icon of a baby and time of the account.

**Comment by diegoberaldin** [comment]
Ok, the "bot" one is easy because it's a property of Lemmy accounts, as for the other one... I never realized what on earth the baby face meant on Voyager :joy: this one really blew my mind... 

In any case, we have the creation date of the profile but I am unsure whether adding too many information in the comment list is actually useful, after all one can enter the user detail and see the "Lemmy-birthday" of the user from there.

**Comment by pfaca** [comment]
> Ok, the "bot" one is easy because it's a property of Lemmy accounts, as for the other one... I never realized what on earth the baby face meant on Voyager 😂 this one really blew my mind...

😂 I only realized it because of the time stamp after. And even that took a couple of times...

> In any case, we have the creation date of the profile but I am unsure whether adding too many information in the comment list is actually useful, after all one can enter the user detail and see the "Lemmy-birthday" of the user from there.

Yeah, fair point. You don't want to "clutter" the layout with to many info. But I think the bot one is important, the baby face not so much and the time of the account its not needed at all.
