### ISSUE TITLE
[Stability] Frequent crashes while switching feeds

### ISSUE THREAD

**Issue by tsievert** [diegoberaldin/RaccoonForLemmy#829]
**Describe the bug**
Since 1.10.0 I observed an increase in crashes when switching between feeds (e.g. from Subscribed to All).
Unfortunately I am unable to reliably reproduce the circumstances, but about 40% of switches result in a crash.
The issue is also present in 1.10.1.

Not sure if related, but it seems as if the login takes longer during the app start. The option to switch feed only becomes available after 30-60 seconds, before you can chose the instance for anonymous browsing.

**To Reproduce**
1. Open app
2. Tap to navbar to bring up different feeds
3. Tap different feed than current
4. Crash

**Expected behavior**
No crash, as it was pre 1.10.0

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 14
 - Version 1.10.0 & 1.10.1

**Comment by diegoberaldin** [comment]
Thanks for the report, I found some hint in the Google play console and was even able to reproduce it systematically, e.g. if you activate lazy scrolling (aka "zombie mode") and you change the feed type in the meantime. But that is just a way to reproduce it, it could happen under other circumstances too. Since this deserves a hotfix, I think I am going to release a 1.10.2 version this weekend.
