### ISSUE TITLE
[Feature request] Option to increase indentation in comment chains

### ISSUE THREAD

**Issue by tsievert** [diegoberaldin/RaccoonForLemmy#833]
**Is your feature request related to a problem? Please describe.**
It is quite difficult for me to properly distinguish on which level a comment belongs in a longer comment chain.
I currently have the comment bar thickness at 3.

**Describe the solution you'd like**
Add an option to separately increase the indentation of comments independently of the comment bar thickness.

**Describe alternatives you've considered**
Allow for values greater than 3 in the comment bar thickness. Additionally (optional) avoid an overlap of the bars, so that the bar of the parent comment would never touch the child's bar if it would continue downwards.

**Comment by diegoberaldin** [comment]
There is room for improvements, I totally agree on this (and some review on the store was pointing in the same direction recently).

We can discuss and probably during this week I'll come up with some proposals that you can evaluate, if you agree!
Thanks for the request in the meantime.

**Comment by tsievert** [comment]
Thanks a lot for reacting so extremely quickly!
And sorry for opening so many issues today

**Comment by diegoberaldin** [comment]
Hi! I am inclined towards option 1, i.e. adding more values to the bar thickness and, at the same time, having the possibility to configure the indent amount (which will be multiplied for the depth of the comment).

I intend to add a 2° level comment to the content preview screen in order to make it easier to see the result in real-time, as  well as using "+" and "-" buttons to adjust both settings. The accepted ranges will be [1, 5] for the bar thickness and [1, 20] for the indent amount.

Here is a snapshot of what it may look like:
<table align="center">
<tr>
<td>
<img src="https://github.com/diegoberaldin/RaccoonForLemmy/assets/2738294/7c45fccb-2c23-488f-b74a-618557367f80" width="310" />
</td>
<td>
<img src="https://github.com/diegoberaldin/RaccoonForLemmy/assets/2738294/b968b0a7-60eb-4fe3-bad5-d0d2aff09447" width="310" />
</td>
</tr>
</table>

What do you think about it?

An additional question, why did you mention overlapping of the bars some comments earlier? Are there any issues due to which you were seeing overlaps, i. e. the bar superimposing on comment text or on each other, in contrast with the screenshot that I am attaching here?

**Comment by tsievert** [comment]
The screenshots look great! I think that's a good solution.

Regarding the bars. I explained that badly. I did not refer to an actual overlap, but note to an optical illusion so to speak.
Imagine the comment bars would go down the entire length of the comment chain (as some other apps do it). In the current form the bars would overlap in that hypothetical case, and I think that's part of the reason why it's so difficult for me to see.
But judging by the second picture, that doesn't seem to be an issue anymore.

**Comment by diegoberaldin** [comment]
Ok, let's proceed down this way then, I'll include this (a little more polished, in the screenshot above there was an uneven padding in the options for example) in the next dev build and I am open to feedback (as always) after you try it.
