### ISSUE TITLE
[post list] Missing unsubscribe button from community while in wait list

### ISSUE THREAD

**Issue by NicKoehler** [diegoberaldin/RaccoonForLemmy#932]
**Describe the bug**
When subscribing to a community with a wait list is not possibile to unsubscribe. 

**To Reproduce**
- go to [this community](https://lemmy.world/c/syncforlemmy)
- subscribe with the + button
- try to unsubscribe

**Expected behavior**
I expect to be able to unsubscribe pressing the dots in the right upper corner.

**Screenshots**
![Screenshot_20240605-145702~2.png](https://github.com/diegoberaldin/RaccoonForLemmy/assets/53040044/17f5c876-88fc-4a08-b358-40aafbcf8010)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 14
 - Version 1.11.0

**Comment by diegoberaldin** [comment]
Yes I confirm the behavior, I remember having removed the possibility to unsubscribe until you are actually subscribed.

I'll check what the Lemmy APIs return if you try to do it and, in case the operation is successful I'll let you do it.

**Comment by diegoberaldin** [comment]
I confirm it can be done, rejoice ye people in all the realm! Additionally, I took the occasion to ask for a confirmation before sending the request to unsubscribe, because it is a "risky" operation and a double confirmation is needed.

This is a part of the app I remember writing last summer in vacation, there are parts  of the community detail dating back to August last year, I had very little time to code as was always in a hurry at night time  :beach_umbrella:

**Comment by NicKoehler** [comment]
Still the best client I ever used tbh, thank you!
